# Generated by Django 3.0.1 on 2020-06-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_voice_model',
            name='voice',
            field=models.TextField(max_length=140),
        ),
    ]
