# Generated by Django 3.0.7 on 2020-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0002_auto_20200604_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_voice_model',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
