# Generated by Django 3.0.7 on 2020-06-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0005_user_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='qa_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
