# Generated by Django 3.0.7 on 2020-06-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0006_qa_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('number', models.IntegerField(default=0)),
                ('p', models.TextField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='answer',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qa_model',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
