# Generated by Django 3.0.7 on 2020-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0007_auto_20200613_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_voice_model',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
