# Generated by Django 3.0.7 on 2020-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0010_account_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_meta',
            name='img',
        ),
        migrations.AddField(
            model_name='user_meta',
            name='top',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_meta',
            name='uid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user_meta',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
