# Generated by Django 3.0.7 on 2020-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0011_auto_20200614_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_meta',
            name='user',
        ),
    ]
