# Generated by Django 3.0.7 on 2020-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0012_auto_20200614_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_meta',
            name='afi_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
