# Generated by Django 3.0.7 on 2020-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0013_auto_20200614_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_user_model',
            name='user',
        ),
        migrations.AddField(
            model_name='message_user_model',
            name='uid',
            field=models.CharField(blank=True, default='technext', max_length=500, null=True),
        ),
    ]
