# Generated by Django 3.0.7 on 2020-06-14 20:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0014_auto_20200615_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customer_voice_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
