# Generated by Django 3.0.7 on 2020-06-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0015_auto_20200615_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog_model',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='customer_voice_model',
            old_name='img',
            new_name='image',
        ),
    ]
