# Generated by Django 3.0.7 on 2020-06-18 03:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0016_auto_20200618_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_model',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/hlbrfvwak/image/upload/v1592409791/vaqfgeeaghdbgjcsghg1.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='customer_voice_model',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/hlbrfvwak/image/upload/v1592409791/vaqfgeeaghdbgjcsghg1.jpg', max_length=255, verbose_name='image'),
        ),
    ]
