# Generated by Django 3.0.7 on 2020-06-19 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0019_c_v_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_user_model',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
