# Generated by Django 3.0.7 on 2020-06-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0021_message_user_model_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_user_model',
            name='afi_code',
            field=models.IntegerField(default=0),
        ),
    ]
