# Generated by Django 3.0.7 on 2020-06-20 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0022_message_user_model_afi_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table_model',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
