# Generated by Django 3.0.7 on 2020-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosou', '0023_message_table_model_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_table_model',
            name='name',
            field=models.CharField(default='aiueo', max_length=150),
        ),
    ]
